import { Permission, RoleType, DEFAULT_ROLES } from "../types/rbac";

export const ROLE_PERMISSIONS: Record<RoleType, Permission[]> = {
  [DEFAULT_ROLES.OWNER]: [
    "properties.view",
    "properties.create",
    "properties.edit",
    "properties.delete",
    "units.view",
    "units.create",
    "units.edit",
    "units.delete",
    "leases.view",
    "leases.create",
    "leases.edit",
    "leases.delete",
    "reports.view",
    "reports.create",
    "payments.view",
    "payments.create",
    "users.invite",
    "users.manage",
  ],
  [DEFAULT_ROLES.ADMIN]: [
    "properties.view",
    "properties.create",
    "properties.edit",
    "units.view",
    "units.create",
    "units.edit",
    "leases.view",
    "leases.create",
    "leases.edit",
    "reports.view",
    "reports.create",
    "payments.view",
    "payments.create",
    "users.invite",
  ],
  [DEFAULT_ROLES.PROPERTY_MANAGER]: [
    "properties.view",
    "properties.edit",
    "units.view",
    "units.create",
    "units.edit",
    "leases.view",
    "leases.create",
    "reports.view",
    "payments.view",
  ],
  [DEFAULT_ROLES.STAFF]: [
    "properties.view",
    "units.view",
    "leases.view",
    "reports.view",
    "payments.view",
  ],
  [DEFAULT_ROLES.VIEWER]: ["properties.view", "units.view", "leases.view"],
};
